[package]
name = "linkedlist"
version = "0.1.0"
authors = ["ollipa <olli@paakkunainen.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "linkedlist"
path = "src/lib.rs"


[dependencies]
